<script type="text/javascript">
    $(function() {
        var langField = $('#activeLanguagesList');
        $('#tabs').tabs()
            .on('change', '#language', function(){
                var langs = langField.val();
                langs = langs.split(',');
                var langsIndex = langs.indexOf($('#language').val());
                if(langsIndex !== -1) {
                    langs.splice(langsIndex);
                    $('#activeLanguagesList').val(langs);
                }
            })
            .on('submit', function(){
                showSpinner($(this));
            });
        $('input[title], .tooltip').tooltip({
            track: true
        });
        $('.tooltip-localization').tooltip({
            track: true,
            content : "<?php echo $this->translate('Replace is checked - replace the previous localization on new localization'); ?> <hr class=\"mt5px mb5px\"> <?php echo $this->translate('Replace isn\'t checked - clone the previous localization with new localization params'); ?>"
        });

        // Join localizations for save
        var localFilds = $('#localizationForm-config');
        localFilds.on('change', 'input.lang-select', function() {
            $('#activeLanguagesList', localFilds).val(
                $(':checked', localFilds).map(function() {
                    return this.getAttribute('data-lang');
                }).get().join(',')
            );
        });
    });
</script>
<div class="seotoaster container">
    <?php echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array('helpSection' => $this->helpSection)
    ); ?>
    <form id="tabs" action="<?php echo $this->configForm->getAction(); ?>" method="<?php echo $this->configForm->getMethod(); ?>">
        <input type="hidden" name="secureToken" value="<?php echo $this->secureToken;?>" />
        <ul class="header">
            <li><a href="#general-config"><?php echo $this->translate('General'); ?></a></li>
            <li><a href="#email-config"><?php echo $this->translate('Email settings'); ?></a></li>
            <?php if ($this->isSuperAdmin): ?>
                <li><a href="#security-config"><?php echo $this->translate('Admin access'); ?></a></li>
                <li><a href="#advanced-config"><?php echo $this->translate('Advanced'); ?></a></li>
                <li><a href="#securityForm-config"><?php echo $this->translate('Security'); ?></a></li>
                <li><a href="#localizationForm-config"><?php echo $this->translate('Localization'); ?></a></li>
            <?php endif; ?>
        </ul>
        <fieldset id="general-config" class="content-small-footer pr0 pl0">
            <div class="grid_5"><?php echo $this->configForm->getElement('language')->renderLabel(); ?></div>
            <div class="grid_2 alpha omega mt0px"><?php echo $this->configForm->getElement('language')->renderViewHelper(); ?></div>
            <label class="grid_5 text-right mt5px tooltip-localization" title="<?php echo $this->translate("Replace the previous localization?"); ?>">
                <?php echo $this->translate("Replace the previous localization?"); ?>
                <input type="checkbox" name="replaceLocalization" id="replaceLocalization">
            </label>
            <div class="grid_5 cl-both"><label><?php echo $this->translate('Image size'); ?></label></div>
            <div class="grid_7 alpha">
                <?php echo $this->configForm->getElement('imgSmall')->renderViewHelper(); ?>
                <?php echo $this->configForm->getElement('imgMedium')->renderViewHelper(); ?>
                <?php echo $this->configForm->getElement('imgLarge')->renderViewHelper(); ?>
            </div>
            <div class="grid_5"><?php echo $this->configForm->getElement('teaserSize')->renderLabel(); ?></div>
            <div class="grid_7 alpha"><?php echo $this->configForm->getElement('teaserSize')->renderViewHelper(); ?></div>
            <div class="grid_5">
                <?php echo $this->configForm->getElement('memPagesInMenu')->renderLabel(); ?>
            </div>
            <div class="grid_1 alpha">
                <?php echo $this->configForm->getElement('memPagesInMenu')->renderViewHelper(); ?>
            </div>
            <div class="grid_5 text-right">
                <?php echo $this->configForm->getElement('enableMinify')->renderLabel(); ?>
            </div>
            <div class="grid_1">
                <?php echo $this->configForm->getElement('enableMinify')->renderViewHelper(); ?>
            </div>
            <div class="grid_5">
                <?php echo $this->configForm->getElement('controlPanelStatus')->renderLabel(); ?>
            </div>
            <div class="grid_1 alpha">
                <?php echo $this->configForm->getElement('controlPanelStatus')->renderViewHelper(); ?>
            </div>
            <div class="grid_5 text-right">
                <?php echo $this->configForm->getElement('enableDeveloperMode')->renderLabel(); ?>
            </div>
            <div class="grid_1">
                <?php echo $this->configForm->getElement('enableDeveloperMode')->renderViewHelper(); ?>
            </div>
            <?php if($this->configForm->getElement('enableDeveloperMode')->getValue()): ?>
            <p class="warning message grid_12">
                <?php echo '<strong>' . $this->translate("Attention!") . '</strong> '. $this->translate("When enabled \"Developer mode\" disables some functionality that speeds up your sites. Do not forget to turn off the \"Developer mode\" after work."); ?>
            </p>
            <?php endif; ?>

            <?php echo $this->configForm->getElement('currentTheme'); ?>
            <?php echo $this->configForm->getElement('adminEmail'); ?>
            <?php echo $this->configForm->getElement('superadminLogin'); ?>
            <div class="hidden"><input type="text" value=""/></div>
            <?php echo $this->configForm->getElement('superadminPassword'); ?>

        </fieldset>
        <fieldset id="email-config" class="content-small-footer pr0 pl0 pt20px">
            <div class="grid_3 text-bold"><?php echo $this->configForm->getElement('useSmtp')->renderLabel(); ?></div>
            <div class="grid_9 mt0px"><?php echo $this->configForm->getElement('useSmtp')->renderViewHelper(); ?></div>
            <div class="grid_6 cl-both">
                <?php echo $this->configForm->getElement('smtpHost')->renderLabel(); ?>
                <?php echo $this->configForm->getElement('smtpHost')->renderViewHelper(); ?>
            </div>
            <div class="grid_4 alpha">
                <?php echo $this->configForm->getElement('smtpPort')->renderLabel(); ?>
                <?php echo $this->configForm->getElement('smtpPort')->renderViewHelper(); ?>
            </div>
            <div class="grid_2 alpha">
                <?php echo $this->configForm->getElement('smtpSsl')->renderLabel(); ?>
                <?php echo $this->configForm->getElement('smtpSsl')->renderViewHelper(); ?>
            </div>
            <div class="grid_12"><?php echo $this->configForm->getElement('smtpLogin'); ?></div>
            <div class="grid_12"><?php echo $this->configForm->getElement('smtpPassword'); ?></div>
        </fieldset>

        <?php if ($this->isSuperAdmin): ?>
            <fieldset id="security-config" class="content-small-footer pt50px">
                <div><?php echo $this->configForm->getElement('suLogin'); ?></div>
                <div><?php echo $this->configForm->getElement('suPassword'); ?></div>
            </fieldset>
            <fieldset id="advanced-config" class="content-small-footer pr0 pl0">
                <div class="fl-left ml-grid mr-grid mt5px"><?php echo $this->configForm->getElement('canonicalScheme')->renderLabel(); ?></div>
                <div class="fl-left mr1 mt0px"><?php echo $this->configForm->getElement('canonicalScheme')->renderViewHelper(); ?></div>
                <div class="wrap mt5px">://<?php echo parse_url($this->websiteUrl, PHP_URL_HOST); ?></div>

                <div class="cl-both grid_6 mt20px">
                    <div class="grid_7 alpha">
                        <?php echo $this->configForm->getElement('mediaServers')->renderLabel(); ?>
                    </div>
                    <div class="grid_5 omega">
                        <?php echo $this->configForm->getElement('mediaServers')->renderViewHelper(); ?>
                    </div>
                    <div class="grid_12 alpha omega mt10px">
                        <em><?php echo $this->translate(
                                'Speed up your site. Insert the following CNAME records into your DNS server:'
                            ); ?></em>
                        <ul class="mt10px mb0px">
                            <?php
                            $host = parse_url($this->websiteUrl, PHP_URL_HOST);
                            $host = str_replace('www.', '', $host);
                            $medias = Zend_Registry::get('website');
                            ?>
                            <?php foreach ($medias['mediaServers'] as $media): ?>
                                <li class="mb0px"><?php echo $media . '.' . $host; ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
                <div class="grid_6 mt20px">
                    <div class="grid_10 alpha">
                        <?php echo $this->configForm->getElement('inlineEditor')->renderLabel(); ?>
                    </div>
                    <div class="grid_2 omega">
                        <?php echo $this->configForm->getElement('inlineEditor')->renderViewHelper(); ?>
                    </div>
                    <div class="grid_12 alpha omega mt10px h150px wrap">
                        <a href="<?php echo $this->websiteUrl; ?>system/images/zonehighlighting.jpg" class="_lbox help">
                            <img src="<?php echo $this->websiteUrl; ?>system/images/zonehighlighting.jpg" class="h150"/>
                        </a>
                    </div>
                </div>

            </fieldset>
            <fieldset id="securityForm-config" class="content-small-footer pt50px">
                <div><?php echo $this->configForm->getElement(Tools_System_Tools::RECAPTCHA_PUBLIC_KEY); ?></div>
                <div><?php echo $this->configForm->getElement(Tools_System_Tools::RECAPTCHA_PRIVATE_KEY); ?></div>
                <div class="mt15px">
                    <a target="_blank" href="https://www.google.com/recaptcha/admin/create"><?php echo $this->translate(
                            'Get your own reCAPTCHA key here now.'
                        ); ?></a>
                </div>
            </fieldset>
            <fieldset id="localizationForm-config" class="content-small-footer scroll">
                <h3><?php echo $this->translate('Select website localization'); ?>:</h3>
                <div class="column_3 full-width">
                    <?php
                    $activeLanguagesList = $this->configForm->getElement('activeLanguagesList')->getValue();
                    $activeLanguagesList = !empty($activeLanguagesList) ? explode(',', $activeLanguagesList) : array();
                    foreach ($this->langList as $key => $value):
                    if ($this->langDefault !== $key):
                    ?>
                    <label class="pointer background" for="lang-<?php echo $value['language']; ?>">
                        <input id="lang-<?php echo $key; ?>"
                               class="lang-select fl-right switcher"
                               type="checkbox"
                               data-lang="<?php echo $key; ?>"
                               name="localization-<?php echo $key; ?>"
                               <?php echo (in_array($key, $activeLanguagesList, true)) ? 'checked="checked"' : ''; ?>>
                               <img class="align-baseline"
                                    border="0"
                                    alt="<?php echo $value['language']; ?>"
                                    src="<?php echo $this->websiteUrl.$value['flag']; ?>">
                    </label>
                    <?php endif; ?>
                    <?php endforeach; ?>
                </div>
                <?php echo $this->configForm->getElement('activeLanguagesList')->renderViewHelper(); ?>
            </fieldset>
        <?php endif; ?>
        <?php echo $this->configForm->getElement('submit')->renderViewHelper(); ?>
    </form>
</div>
