<?php if (!empty($this->headerText) || !empty($this->innerHeaderHtml)): ?>
<div class="header">
<?php endif;?>

<div class="closebutton">
	<!-- Local section start -->
	<?php if (!empty($this->langSection)):
        $website = Zend_Controller_Action_HelperBroker::getStaticHelper('website');
        echo '<div class="btn-set">'; ?>
		<?php foreach ($this->langSection as $code => $val): ?>
			<a class="language-link mr5px <?php if (!$val['active']) echo 'fade'; ?>"
				href="<?php echo $val['href']; ?>"
				title="<?php echo $val['title']; ?>">
				<img border="0" src="<?php echo $website->getUrl(); ?>system/images/flags/<?php echo $code; ?>.png" width="18"
                    alt="<?php echo $val['title']; ?>">
			</a>
		<?php endforeach;
        echo '</div>'; ?>
	<?php elseif (Tools_Localization_Tools::getActiveLanguagesList() && isset($this->langSection)): ?>
        <span class="warning small"><?php echo $this->translate('Apply the changes to add translation');?></span>
	<?php endif; ?>
	<!-- Local section end -->

	<?php if(isset($this->helpSection)){
        echo $this->toasterHelp($this->helpSection, $this->hashMap);
    } ?>
    <a class="close ticon-close" href="javascript:;" title="<?php echo $this->translate('Close'); ?>"></a>
</div>

<?php echo (isset($this->headerText) ? $this->translate($this->headerText) : ''); ?>
<?php if(isset($this->innerHeaderHtml) && $this->innerHeaderHtml): ?>
	<?php echo $this->innerHeaderHtml; ?>
<?php endif; ?>

<?php if(isset($this->pluginsSpace) && is_array($this->pluginsSpace) && !empty ($this->pluginsSpace)): ?>
	<div class="pluginspace">
		<?php foreach($this->pluginsSpace as $pluginEditorTop): ?>
			<div class="<?php echo (isset($pluginEditorTop['title']) ? $pluginEditorTop['title']: ''); ?>">
				<?php echo(isset($pluginEditorTop['code']) ? $pluginEditorTop['code'] : ''); ?>
			</div>
		<?php endforeach; ?>
	</div>
<?php endif; ?>

<?php if (!empty($this->headerText) || !empty($this->innerHeaderHtml)): ?>
</div>
<?php endif;?>